services:
  dockermongodb:
    image: mongo:latest
    #    restart: always
    container_name: dockermongodb
    ports:
      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: password
#    volumes:
#      - type: bind
#        source: ./data
#        target: /data/db

  springboot-mongodb:
    image: sahil-sb-mongodb
    container_name: springboot-mongodb-app
    build: .
    environment:
      JWT_SECRET_BASE64: ${JWT_SECRET_BASE64}
#    env_file:
#      - .env
    ports:
      - 8081:8081
#      - 8080:8080 # swagger runs on the same port as the application
    depends_on:
      - dockermongodb
